import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import forge from 'node-forge';
import { SignedXml } from 'xml-crypto';
import { DOMParser } from '@xmldom/xmldom';
import { config } from './config.js';

const NS={soap:'http://schemas.xmlsoap.org/soap/envelope/',nfse:'http://nfse.abrasf.org.br',cab:'http://www.giss.com.br/cabecalho-v2_04.xsd',envio:'http://www.giss.com.br/enviar-lote-rps-envio-v2_04.xsd',tipos:'http://www.giss.com.br/tipos-v2_04.xsd',ds:'http://www.w3.org/2000/09/xmldsig#'};
const ALG={c14n:'http://www.w3.org/TR/2001/REC-xml-c14n-20010315',env:'http://www.w3.org/2000/09/xmldsig#enveloped-signature',rsa:'http://www.w3.org/2000/09/xmldsig#rsa-sha1',sha:'http://www.w3.org/2000/09/xmldsig#sha1'};
const x=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const digits=v=>String(v??'').replace(/\D/g,'');
const cdata=s=>`<![CDATA[${String(s).replace(/]]>/g,']]]]><![CDATA[>')}]]>`;
function err(message,status=400,details=null){const e=new Error(message);e.status=status;e.details=details;return e;}
function certPath(){const p=String(config.giss.certPfxPath||'').trim();return p?(path.isAbsolute(p)?p:path.resolve(process.cwd(),p)):'';}
export function getGissConfigStatus(){const p=certPath(),missing=[];if(digits(config.giss.cnpj).length!==14)missing.push('GISS_CNPJ');if(!config.giss.inscricaoMunicipal)missing.push('GISS_INSCRICAO_MUNICIPAL');if(!config.giss.serviceUrl)missing.push('GISS_SERVICE_URL');if(!config.giss.wsdlUrl)missing.push('GISS_WSDL_URL');if(!p)missing.push('GISS_CERT_PFX_PATH');if(!config.giss.certPassword)missing.push('GISS_CERT_PASSWORD');if(p&&!fs.existsSync(p))missing.push('arquivo do certificado não encontrado');return{configured:!missing.length,ambiente:config.giss.env,wsdl:config.giss.wsdlUrl,endpoint:config.giss.serviceUrl,certificadoEncontrado:!!p&&fs.existsSync(p),missing};}
function assertCfg(){const s=getGissConfigStatus();if(!s.configured)throw err('Integração Giss ainda não está configurada.',400,s.missing);}
function loadCert(){assertCfg();const pfx=fs.readFileSync(certPath());let p12;try{p12=forge.pkcs12.pkcs12FromAsn1(forge.asn1.fromDer(forge.util.createBuffer(pfx.toString('binary'))),false,config.giss.certPassword);}catch(e){throw err('Não consegui abrir o certificado A1.',400,e.message);}const kb=p12.getBags({bagType:forge.pki.oids.pkcs8ShroudedKeyBag})[forge.pki.oids.pkcs8ShroudedKeyBag]||[];const pk=p12.getBags({bagType:forge.pki.oids.keyBag})[forge.pki.oids.keyBag]||[];const cb=p12.getBags({bagType:forge.pki.oids.certBag})[forge.pki.oids.certBag]||[];const key=(kb[0]||pk[0])?.key,cert=cb[0]?.cert;if(!key||!cert)throw err('Certificado A1 sem chave privada utilizável.');const certPem=forge.pki.certificateToPem(cert);return{pfx,privateKeyPem:forge.pki.privateKeyToPem(key),certPem};}
function request(urlString,{method='GET',headers={},body=null}={}){const {pfx}=loadCert(),url=new URL(urlString);return new Promise((resolve,reject)=>{const q=https.request({protocol:url.protocol,hostname:url.hostname,port:url.port||443,path:url.pathname+url.search,method,headers:{'User-Agent':'BRCONDOS-Financeiro/1.0',...headers},pfx,passphrase:config.giss.certPassword,minVersion:'TLSv1.2',rejectUnauthorized:true},r=>{const a=[];r.on('data',c=>a.push(c));r.on('end',()=>resolve({status:r.statusCode||0,text:Buffer.concat(a).toString('utf8')}));});q.on('error',reject);if(body)q.write(body);q.end();});}
function els(doc,name){const out=[],all=doc.getElementsByTagName('*');for(let i=0;i<all.length;i++)if((all[i].localName||all[i].nodeName.split(':').pop())===name)out.push(all[i]);return out;}
function txt(doc,names){for(const n of names){const s=els(doc,n)[0]?.textContent?.trim();if(s)return s;}return'';}
function extract(soap){const d=new DOMParser().parseFromString(soap,'text/xml');for(const n of ['outputXML','return','RecepcionarLoteRpsResult','ConsultarLoteRpsResult','ConsultarNfseServicoPrestadoResult','ConsultarNfsePorRpsResult']){const s=els(d,n)[0]?.textContent?.trim();if(s)return s;}return soap;}
function parse(xml){const d=new DOMParser().parseFromString(xml,'text/xml');const erros=els(d,'MensagemRetorno').map(e=>({codigo:txt(e,['Codigo']),mensagem:txt(e,['Mensagem']),correcao:txt(e,['Correcao']),rpsNumero:txt(els(e,'IdentificacaoRps')[0]||e,['Numero'])})).filter(e=>e.codigo||e.mensagem);const cancelamentos=els(d,'NfseCancelamento').map(e=>({numero:txt(e,['Numero']),dataCancelamento:txt(e,['DataHora']),codigoCancelamento:txt(e,['CodigoCancelamento'])}));const nfse=els(d,'InfNfse').map(e=>{const r=els(e,'IdentificacaoRps')[0];return{idInterno:e.getAttribute('Id')||'',numero:txt(e,['Numero']),codigoVerificacao:txt(e,['CodigoVerificacao']),dataEmissao:txt(e,['DataEmissao']),rpsNumero:r?txt(r,['Numero']):'',cancelada:false,dataCancelamento:'',codigoCancelamento:''};});return{sucesso:erros.length===0&&(nfse.length>0||!/ListaMensagemRetorno/i.test(xml)),protocolo:txt(d,['Protocolo']),numeroLote:txt(d,['NumeroLote']),situacao:txt(d,['Situacao','Situação']),nfse,cancelamentos,erros};}
function sign(xmlText,target='/*',empty=false){const c=loadCert();const s=new SignedXml({privateKey:c.privateKeyPem,publicCert:c.certPem,signatureAlgorithm:ALG.rsa,canonicalizationAlgorithm:ALG.c14n,getKeyInfoContent:SignedXml.getKeyInfoContent});s.addReference({xpath:target,transforms:[ALG.env,ALG.c14n],digestAlgorithm:ALG.sha,...(empty?{isEmptyUri:true}:{})});s.computeSignature(xmlText,{prefix:'ds',location:{reference:target,action:target==='/*'?'append':'after'},existingPrefixes:{giss:NS.envio,tipos:NS.tipos,ds:NS.ds}});return s.getSignedXml();}
function head(){return `<cabecalho xmlns="${NS.cab}" versao="${x(config.giss.versao)}"><versaoDados>${x(config.giss.versao)}</versaoDados></cabecalho>`;}
function soap(operation,dataXml){return `<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="${NS.soap}" xmlns:nfse="${NS.nfse}"><soapenv:Header/><soapenv:Body><nfse:${operation}Request><nfseCabecMsg>${cdata(head())}</nfseCabecMsg><nfseDadosMsg>${cdata(dataXml)}</nfseDadosMsg></nfse:${operation}Request></soapenv:Body></soapenv:Envelope>`;}
async function post(operation,dataXml){const envelope=soap(operation,dataXml);const r=await request(config.giss.serviceUrl,{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','SOAPAction':`"http://nfse.abrasf.org.br/${operation}"`,'Content-Length':Buffer.byteLength(envelope)},body:envelope});if(r.status<200||r.status>=300)throw err(`Giss respondeu HTTP ${r.status}.`,502,r.text.slice(0,1500));const out=extract(r.text);return{...parse(out),ambiente:config.giss.env,xmlRetorno:out};}
export async function testGissWsdl(){const r=await request(config.giss.wsdlUrl);if(r.status<200||r.status>=300||!/<(?:wsdl:)?definitions/i.test(r.text))throw err(`Giss respondeu HTTP ${r.status} ao abrir o WSDL.`,502);return{ok:true,ambiente:config.giss.env,endpoint:config.giss.serviceUrl,wsdl:config.giss.wsdlUrl,metodos:[...new Set([...r.text.matchAll(/operation\s+name=["']([^"']+)["']/gi)].map(m=>m[1]))].filter(n=>/Nfse|Rps/i.test(n)).slice(0,30)};}
function tomador(t){if(!t)throw err('Tomador não informado.');const doc=digits(t.documento||t.doc),nome=String(t.nome||t.name||'').trim(),mun=digits(t.codigoMunicipio||t.cityIbge),cep=digits(t.cep||t.zip),uf=String(t.uf||t.state||'').trim().toUpperCase(),end=String(t.endereco||t.street||'').trim(),num=String(t.numero||t.number||'').trim(),bairro=String(t.bairro||t.district||'').trim();if(![11,14].includes(doc.length)||!nome||!end||!num||!bairro||mun.length!==7||uf.length!==2||cep.length!==8)throw err('Complete o cadastro do tomador.');const dc=doc.length===14?`<tipos:Cnpj>${doc}</tipos:Cnpj>`:`<tipos:Cpf>${doc}</tipos:Cpf>`;return `<tipos:TomadorServico><tipos:IdentificacaoTomador><tipos:CpfCnpj>${dc}</tipos:CpfCnpj></tipos:IdentificacaoTomador><tipos:RazaoSocial>${x(nome)}</tipos:RazaoSocial><tipos:Endereco><tipos:Endereco>${x(end)}</tipos:Endereco><tipos:Numero>${x(num)}</tipos:Numero><tipos:Bairro>${x(bairro)}</tipos:Bairro><tipos:CodigoMunicipio>${mun}</tipos:CodigoMunicipio><tipos:Uf>${uf}</tipos:Uf><tipos:Cep>${cep}</tipos:Cep></tipos:Endereco></tipos:TomadorServico>`;}
function rps(item,i){const nr=digits(item.numeroRps||item.rps||String(i+1)),valor=Number(item.valor),aliq=Number(item.aliquotaPct??item.aliquota),data=String(item.dataEmissao||''),comp=String(item.competencia||''),id=`RPS${nr}`;if(!nr||!Number.isFinite(valor)||!Number.isFinite(aliq)||!/^\d{4}-\d{2}-\d{2}$/.test(data)||!/^\d{4}-\d{2}-\d{2}$/.test(comp))throw err('Dados do RPS inválidos.');const a=(aliq>1?aliq/100:aliq).toFixed(4),ind=digits(config.giss.indicadorOperacao),cst=digits(config.giss.cstIbsCbs),cl=digits(config.giss.classificacaoTributaria),loc=digits(config.giss.localidadeIncidencia);const ibs=`<tipos:IBSCBS><tipos:finNFSe>0</tipos:finNFSe><tipos:indFinal>0</tipos:indFinal>${ind?`<tipos:cIndOp>${ind}</tipos:cIndOp>`:''}<tipos:tpOper>1</tipos:tpOper><tipos:tpEnteGov>4</tipos:tpEnteGov><tipos:indDest>0</tipos:indDest><tipos:valores><tipos:trib><tipos:gIBSCBS><tipos:CST>${cst}</tipos:CST><tipos:cClassTrib>${cl}</tipos:cClassTrib></tipos:gIBSCBS></tipos:trib><tipos:cLocalidadeIncid>${loc}</tipos:cLocalidadeIncid><tipos:pRedutor>0.00</tipos:pRedutor></tipos:valores></tipos:IBSCBS>`;return{id,nr,xml:`<tipos:Rps><tipos:InfDeclaracaoPrestacaoServico Id="${id}"><tipos:Rps><tipos:IdentificacaoRps><tipos:Numero>${nr}</tipos:Numero><tipos:Serie>${x(config.giss.serieRps)}</tipos:Serie><tipos:Tipo>1</tipos:Tipo></tipos:IdentificacaoRps><tipos:DataEmissao>${data}</tipos:DataEmissao><tipos:Status>1</tipos:Status></tipos:Rps><tipos:Competencia>${comp}</tipos:Competencia><tipos:Servico><tipos:Valores><tipos:ValorServicos>${valor.toFixed(2)}</tipos:ValorServicos><tipos:Aliquota>${a}</tipos:Aliquota>${ibs}</tipos:Valores><tipos:IssRetido>2</tipos:IssRetido><tipos:ItemListaServico>${x(config.giss.itemListaServico)}</tipos:ItemListaServico>${config.giss.codigoTributacaoMunicipio?`<tipos:CodigoTributacaoMunicipio>${x(config.giss.codigoTributacaoMunicipio)}</tipos:CodigoTributacaoMunicipio>`:''}<tipos:Discriminacao>${x(item.discriminacao||item.descricao||config.giss.discriminacaoPadrao)}</tipos:Discriminacao><tipos:CodigoMunicipio>${x(config.giss.codigoMunicipio)}</tipos:CodigoMunicipio><tipos:CodigoPais>0076</tipos:CodigoPais><tipos:ExigibilidadeISS>${x(config.giss.exigibilidadeIss)}</tipos:ExigibilidadeISS><tipos:MunicipioIncidencia>${x(config.giss.codigoMunicipio)}</tipos:MunicipioIncidencia></tipos:Servico><tipos:Prestador><tipos:CpfCnpj><tipos:Cnpj>${digits(config.giss.cnpj)}</tipos:Cnpj></tipos:CpfCnpj><tipos:InscricaoMunicipal>${x(config.giss.inscricaoMunicipal)}</tipos:InscricaoMunicipal></tipos:Prestador>${tomador(item.tomador)}<tipos:OptanteSimplesNacional>${x(config.giss.optanteSimples)}</tipos:OptanteSimplesNacional><tipos:IncentivoFiscal>${x(config.giss.incentivoFiscal)}</tipos:IncentivoFiscal></tipos:InfDeclaracaoPrestacaoServico></tipos:Rps>`};}
export function buildGissPreview(payload,{sign:doSign=false}={}){assertCfg();const itens=Array.isArray(payload?.itens)?payload.itens:[payload],rs=itens.map(rps),numeroLote=digits(payload?.numeroLote||itens[0]?.numeroLote||'1'),lid=`LOTE${numeroLote}`;let data=`<giss:EnviarLoteRpsEnvio xmlns:giss="${NS.envio}" xmlns:tipos="${NS.tipos}" xmlns:ds="${NS.ds}"><giss:LoteRps Id="${lid}" versao="${x(config.giss.versao)}"><tipos:NumeroLote>${numeroLote}</tipos:NumeroLote><tipos:Prestador><tipos:CpfCnpj><tipos:Cnpj>${digits(config.giss.cnpj)}</tipos:Cnpj></tipos:CpfCnpj><tipos:InscricaoMunicipal>${x(config.giss.inscricaoMunicipal)}</tipos:InscricaoMunicipal></tipos:Prestador><tipos:QuantidadeRps>${rs.length}</tipos:QuantidadeRps><tipos:ListaRps>${rs.map(r=>r.xml).join('')}</tipos:ListaRps></giss:LoteRps></giss:EnviarLoteRpsEnvio>`;if(doSign){if(rs.length===1)data=sign(data,`//*[@Id='${rs[0].id}']`);data=sign(data,`//*[@Id='${lid}']`);}return{ambiente:config.giss.env,numeroLote,rps:rs.map(r=>r.nr),headerXml:head(),dataXml:data,assinado:doSign};}
export async function emitirNfseGiss(payload){const p=buildGissPreview(payload,{sign:true});const r=await post('RecepcionarLoteRps',p.dataXml);return{...r,enviado:{numeroLote:p.numeroLote,rps:p.rps}};}
function prestador(){return `<giss:Prestador><tipos:CpfCnpj><tipos:Cnpj>${digits(config.giss.cnpj)}</tipos:Cnpj></tipos:CpfCnpj><tipos:InscricaoMunicipal>${x(config.giss.inscricaoMunicipal)}</tipos:InscricaoMunicipal></giss:Prestador>`;}
export async function consultarLoteRpsGiss(protocolo){assertCfg();const p=String(protocolo||'').trim();if(!p)throw err('Informe o protocolo do lote.');let d=`<giss:ConsultarLoteRpsEnvio xmlns:giss="http://www.giss.com.br/consultar-lote-rps-envio-v2_04.xsd" xmlns:tipos="${NS.tipos}">${prestador()}<giss:Protocolo>${x(p)}</giss:Protocolo></giss:ConsultarLoteRpsEnvio>`;d=sign(d,'/*',true);return{...(await post('ConsultarLoteRps',d)),consulta:{protocolo:p}};}
export async function consultarNfsePorNumeroGiss({numero,pagina=1}){assertCfg();const n=String(numero||'').trim();if(!n)throw err('Informe o número da NFS-e.');const d=`<giss:ConsultarNfseServicoPrestadoEnvio xmlns:giss="http://www.giss.com.br/consultar-nfse-servico-prestado-envio-v2_04.xsd" xmlns:tipos="${NS.tipos}">${prestador()}<giss:NumeroNfse>${x(n)}</giss:NumeroNfse><giss:Pagina>${x(pagina)}</giss:Pagina></giss:ConsultarNfseServicoPrestadoEnvio>`;return{...(await post('ConsultarNfseServicoPrestado',d)),consulta:{numeroNfse:n,pagina:String(pagina)}};}
export async function consultarNfsePorRpsGiss({numero,serie='RPS',tipo=1}){assertCfg();const n=String(numero||'').trim();if(!n)throw err('Informe o número do RPS.');const d=`<giss:ConsultarNfseRpsEnvio xmlns:giss="http://www.giss.com.br/consultar-nfse-rps-envio-v2_04.xsd" xmlns:tipos="${NS.tipos}"><giss:IdentificacaoRps><tipos:Numero>${x(n)}</tipos:Numero><tipos:Serie>${x(serie)}</tipos:Serie><tipos:Tipo>${x(tipo)}</tipos:Tipo></giss:IdentificacaoRps>${prestador()}</giss:ConsultarNfseRpsEnvio>`;return{...(await post('ConsultarNfsePorRps',d)),consulta:{numero:n,serie,tipo:String(tipo)}};}
